/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BrowseRouteImport } from './routes/browse'
import { Route as PopularRouteImport } from './routes/popular'
import { Route as SearchRouteImport } from './routes/search'
import { Route as TrendingRouteImport } from './routes/trending'
import { Route as WatchlistRouteImport } from './routes/watchlist'
import { Route as AnimeIdRouteImport } from './routes/anime.$id'
import { Route as GenresIndexRouteImport } from './routes/genres.index'
import { Route as GenresSlugRouteImport } from './routes/genres.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseRoute = BrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => rootRouteImport,
} as any)
const PopularRoute = PopularRouteImport.update({
  id: '/popular',
  path: '/popular',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const TrendingRoute = TrendingRouteImport.update({
  id: '/trending',
  path: '/trending',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchlistRoute = WatchlistRouteImport.update({
  id: '/watchlist',
  path: '/watchlist',
  getParentRoute: () => rootRouteImport,
} as any)
const AnimeIdRoute = AnimeIdRouteImport.update({
  id: '/anime/$id',
  path: '/anime/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const GenresIndexRoute = GenresIndexRouteImport.update({
  id: '/genres/',
  path: '/genres/',
  getParentRoute: () => rootRouteImport,
} as any)
const GenresSlugRoute = GenresSlugRouteImport.update({
  id: '/genres/$slug',
  path: '/genres/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/browse': typeof BrowseRoute
  '/popular': typeof PopularRoute
  '/search': typeof SearchRoute
  '/trending': typeof TrendingRoute
  '/watchlist': typeof WatchlistRoute
  '/anime/$id': typeof AnimeIdRoute
  '/genres/$slug': typeof GenresSlugRoute
  '/genres/': typeof GenresIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/browse': typeof BrowseRoute
  '/popular': typeof PopularRoute
  '/search': typeof SearchRoute
  '/trending': typeof TrendingRoute
  '/watchlist': typeof WatchlistRoute
  '/anime/$id': typeof AnimeIdRoute
  '/genres/$slug': typeof GenresSlugRoute
  '/genres': typeof GenresIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/browse': typeof BrowseRoute
  '/popular': typeof PopularRoute
  '/search': typeof SearchRoute
  '/trending': typeof TrendingRoute
  '/watchlist': typeof WatchlistRoute
  '/anime/$id': typeof AnimeIdRoute
  '/genres/$slug': typeof GenresSlugRoute
  '/genres/': typeof GenresIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/browse'
    | '/popular'
    | '/search'
    | '/trending'
    | '/watchlist'
    | '/anime/$id'
    | '/genres/$slug'
    | '/genres/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/browse'
    | '/popular'
    | '/search'
    | '/trending'
    | '/watchlist'
    | '/anime/$id'
    | '/genres/$slug'
    | '/genres'
  id:
    | '__root__'
    | '/'
    | '/browse'
    | '/popular'
    | '/search'
    | '/trending'
    | '/watchlist'
    | '/anime/$id'
    | '/genres/$slug'
    | '/genres/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BrowseRoute: typeof BrowseRoute
  PopularRoute: typeof PopularRoute
  SearchRoute: typeof SearchRoute
  TrendingRoute: typeof TrendingRoute
  WatchlistRoute: typeof WatchlistRoute
  AnimeIdRoute: typeof AnimeIdRoute
  GenresSlugRoute: typeof GenresSlugRoute
  GenresIndexRoute: typeof GenresIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse': {
      id: '/browse'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof BrowseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/popular': {
      id: '/popular'
      path: '/popular'
      fullPath: '/popular'
      preLoaderRoute: typeof PopularRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trending': {
      id: '/trending'
      path: '/trending'
      fullPath: '/trending'
      preLoaderRoute: typeof TrendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watchlist': {
      id: '/watchlist'
      path: '/watchlist'
      fullPath: '/watchlist'
      preLoaderRoute: typeof WatchlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anime/$id': {
      id: '/anime/$id'
      path: '/anime/$id'
      fullPath: '/anime/$id'
      preLoaderRoute: typeof AnimeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/genres/': {
      id: '/genres/'
      path: '/genres'
      fullPath: '/genres/'
      preLoaderRoute: typeof GenresIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/genres/$slug': {
      id: '/genres/$slug'
      path: '/genres/$slug'
      fullPath: '/genres/$slug'
      preLoaderRoute: typeof GenresSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BrowseRoute: BrowseRoute,
  PopularRoute: PopularRoute,
  SearchRoute: SearchRoute,
  TrendingRoute: TrendingRoute,
  WatchlistRoute: WatchlistRoute,
  AnimeIdRoute: AnimeIdRoute,
  GenresSlugRoute: GenresSlugRoute,
  GenresIndexRoute: GenresIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
